// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Models;

#nullable disable

namespace WebApplication6.Migrations
{
    [DbContext(typeof(Fm2Context))]
    [Migration("20241213193658_UpdateUserSchema")]
    partial class UpdateUserSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("Prereq")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "Prereq")
                        .HasName("PK__CoursePr__F8693C2CD4B9D900");

                    b.HasIndex("Prereq");

                    b.ToTable("CoursePrerequisite", (string)null);
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .HasColumnType("int")
                        .HasColumnName("GoalID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("GoalId", "LearnerId")
                        .HasName("PK__Learners__3C3540FE56335704");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnersGoals", (string)null);
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("NotificationId", "LearnerId")
                        .HasName("PK__Received__96B591FD251F8963");

                    b.HasIndex("LearnerId");

                    b.ToTable("ReceivedNotification", (string)null);
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.HasKey("InstructorId", "CourseId")
                        .HasName("PK__Teaches__F193DC635A4CB8CE");

                    b.HasIndex("CourseId");

                    b.ToTable("Teaches", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AchievementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    b.Property<DateOnly?>("DateEarned")
                        .HasColumnType("date")
                        .HasColumnName("date_earned");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.HasKey("AchievementId")
                        .HasName("PK__Achievem__276330E0270D96D5");

                    b.HasIndex("BadgeId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Criteria")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int?>("PassingMarks")
                        .HasColumnType("int")
                        .HasColumnName("passing_marks");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int")
                        .HasColumnName("total_marks");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<double?>("Weightage")
                        .HasColumnType("float")
                        .HasColumnName("weightage");

                    b.HasKey("Id")
                        .HasName("PK__Assessme__3214EC271B42907A");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("WebApplication6.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    b.Property<string>("Criteria")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("BadgeId")
                        .HasName("PK__Badge__1918237CE2ED6FF5");

                    b.ToTable("Badge", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Collaborative", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<int?>("MaxNumParticipants")
                        .HasColumnType("int")
                        .HasColumnName("max_num_participants");

                    b.HasKey("QuestId")
                        .HasName("PK__Collabor__B6619ACBA711EE96");

                    b.ToTable("Collaborative", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.ContentLibrary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_URL");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("metadata");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__ContentL__3214EC27C7CFFC8B");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("ContentLibrary", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int?>("CreditPoints")
                        .HasColumnType("int")
                        .HasColumnName("credit_points");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("LearningObjective")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("learning_objective");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D718769AE5F94");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("In Progress")
                        .HasColumnName("status");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Course_e__7F6877FB1FE42095");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Course_enrollment", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.DiscussionForum", b =>
                {
                    b.Property<int>("ForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ForumId")
                        .HasName("PK__Discussi__E210AC4FEBAF192A");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Discussion_forum", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.EmotionalFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activityID");

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emotional_state");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Emotiona__6A4BEDF601950633");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Emotional_feedback", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.EmotionalfeedbackReview", b =>
                {
                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Review")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("review");

                    b.HasKey("FeedbackId", "InstructorId")
                        .HasName("PK__Emotiona__C39BFD41475B7430");

                    b.HasIndex("InstructorId");

                    b.ToTable("Emotionalfeedback_review", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.FilledSurvey", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Answer")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SurveyId", "Question", "LearnerId")
                        .HasName("PK__FilledSu__D89C33C72EB2C16B");

                    b.HasIndex("LearnerId");

                    b.ToTable("FilledSurvey", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.HealthCondition", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.Property<string>("Condition")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("condition");

                    b.HasKey("LearnerId", "ProfileId", "Condition")
                        .HasName("PK__HealthCo__930320B08BD1B855");

                    b.ToTable("HealthCondition", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExpertiseArea")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("expertise_area");

                    b.Property<string>("LatestQualification")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("latest_qualification");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__9D010B7BB682F73F");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.InteractionLog", b =>
                {
                    b.Property<int>("LogId")
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    b.Property<string>("ActionType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("action_type");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_ID");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("LogId")
                        .HasName("PK__Interact__5E5499A82D79211A");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Interaction_log", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Leaderboard", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    b.Property<string>("Season")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("season");

                    b.HasKey("BoardId")
                        .HasName("PK__Leaderbo__F9646BD262AEC362");

                    b.ToTable("Leaderboard", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country");

                    b.Property<string>("CulturalBackground")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cultural_background");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("LearnerId")
                        .HasName("PK__Learner__67ABFCFA3C1358A3");

                    b.HasIndex("UserId1");

                    b.ToTable("Learner", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearnerDiscussion", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Post")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.HasKey("ForumId", "LearnerId")
                        .HasName("PK__LearnerD__546A1380C98B1B35");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnerDiscussion", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearnerMastery", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("completion_status");

                    b.HasKey("LearnerId", "QuestId")
                        .HasName("PK__LearnerM__CCCDE55661334F29");

                    b.HasIndex("QuestId");

                    b.ToTable("LearnerMastery", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearnersCollaboration", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("completion_status");

                    b.HasKey("LearnerId", "QuestId")
                        .HasName("PK__Learners__CCCDE5564F86EFE1");

                    b.HasIndex("QuestId");

                    b.ToTable("LearnersCollaboration", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearningActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("InstructionDetails")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("instruction_details");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("Max_points");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.HasKey("ActivityId")
                        .HasName("PK__Learning__45F4A7F1AEFF5703");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Learning_activities", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearningGoal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Learning__3214EC274D64754A");

                    b.ToTable("Learning_goal", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearningPath", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PathID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PathId"));

                    b.Property<string>("AdaptiveRules")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adaptive_rules");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("completion_status");

                    b.Property<string>("CustomContent")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("custom_content");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.HasKey("PathId")
                        .HasName("PK__Learning__CD67DC3982E2DA3B");

                    b.HasIndex("LearnerId", "ProfileId");

                    b.ToTable("Learning_path", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.LearningPreference", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Preference")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preference");

                    b.HasKey("LearnerId")
                        .HasName("PK__Learning__67ABFCFA0E63C0DE");

                    b.ToTable("LearningPreference", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contentURL");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ModuleId", "CourseId")
                        .HasName("PK__Modules__47E6A09F8FAB8BA4");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("WebApplication6.Models.ModuleContent", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_type");

                    b.HasKey("ModuleId", "CourseId", "ContentType")
                        .HasName("PK__ModuleCo__402E75DAC4BF57E2");

                    b.ToTable("ModuleContent", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<bool?>("ReadStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC2772205947");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Pathreview", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PathID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PathId"));

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Review")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("review");

                    b.HasKey("PathId")
                        .HasName("PK__Pathrevi__CD67DC397034A608");

                    b.HasIndex("InstructorId");

                    b.ToTable("Pathreview", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.PersonalizationProfile", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emotional_state");

                    b.Property<string>("PersonalityType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("personality_type");

                    b.Property<string>("PreferedContentType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Prefered_content_type");

                    b.HasKey("LearnerId", "ProfileId")
                        .HasName("PK__Personal__353B34724B011353");

                    b.ToTable("PersonalizationProfiles");
                });

            modelBuilder.Entity("WebApplication6.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("Criteria")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("QuestId")
                        .HasName("PK__Quest__B6619ACB0A8A239F");

                    b.ToTable("Quest", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.QuestReward", b =>
                {
                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("TimeEarned")
                        .HasColumnType("datetime")
                        .HasColumnName("Time_earned");

                    b.HasKey("RewardId", "QuestId", "LearnerId")
                        .HasName("PK__QuestRew__D251A7C9F490BC4A");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestReward", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Ranking", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.HasKey("BoardId", "LearnerId", "CourseId")
                        .HasName("PK__Ranking__C9D7F96C779E0510");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Ranking", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<int?>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("RewardId")
                        .HasName("PK__Reward__8250159967EEE1CF");

                    b.ToTable("Reward", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Skill", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Skill1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skill");

                    b.HasKey("LearnerId", "Skill1")
                        .HasName("PK__Skills__C45BDEA57D85496C");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("WebApplication6.Models.SkillMastery", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("Skill")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skill");

                    b.HasKey("QuestId", "Skill")
                        .HasName("PK__Skill_Ma__1591B894E525C93A");

                    b.HasIndex(new[] { "QuestId" }, "UQ__Skill_Ma__B6619ACA368F6064")
                        .IsUnique();

                    b.ToTable("Skill_Mastery", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.SkillProgression", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proficiency_level");

                    b.Property<string>("SkillName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skill_name");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PK__SkillPro__3214EC27CFD054FF");

                    b.HasIndex("LearnerId", "SkillName");

                    b.ToTable("SkillProgression", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Survey__3214EC27A0E64281");

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SurveyId", "Question")
                        .HasName("PK__SurveyQu__23FB983B72F26366");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("WebApplication6.Models.Takenassessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("AssessmentID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ScoredPoint")
                        .HasColumnType("int")
                        .HasColumnName("scoredPoint");

                    b.HasKey("AssessmentId", "LearnerId")
                        .HasName("PK__Takenass__8B5147F1FDBF0997");

                    b.HasIndex("LearnerId");

                    b.ToTable("Takenassessment", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.TargetTrait", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Trait")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ModuleId", "CourseId", "Trait")
                        .HasName("PK__Target_t__4E005E4C50307B4F");

                    b.ToTable("Target_traits", (string)null);
                });

            modelBuilder.Entity("WebApplication6.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07950F0667");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534B32F2497")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.HasOne("WebApplication6.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Cours__45F365D3");

                    b.HasOne("WebApplication6.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("Prereq")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Prere__46E78A0C");
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.HasOne("WebApplication6.Models.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersG__GoalI__03F0984C");

                    b.HasOne("WebApplication6.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersG__Learn__04E4BC85");
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Learn__1332DBDC");

                    b.HasOne("WebApplication6.Models.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Notif__123EB7A3");
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.HasOne("WebApplication6.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__CourseI__787EE5A0");

                    b.HasOne("WebApplication6.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__Instruc__778AC167");
                });

            modelBuilder.Entity("WebApplication6.Models.Achievement", b =>
                {
                    b.HasOne("WebApplication6.Models.Badge", "Badge")
                        .WithMany("Achievements")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Badge__1BC821DD");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("Achievements")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Learn__1AD3FDA4");

                    b.Navigation("Badge");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.Assessment", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Assessments__5535A963");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.Collaborative", b =>
                {
                    b.HasOne("WebApplication6.Models.Quest", "Quest")
                        .WithOne("Collaborative")
                        .HasForeignKey("WebApplication6.Models.Collaborative", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Collabora__Quest__2645B050");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebApplication6.Models.ContentLibrary", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("ContentLibraries")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ContentLibrary__52593CB8");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.CourseEnrollment", b =>
                {
                    b.HasOne("WebApplication6.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Cours__73BA3083");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Learn__74AE54BC");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.DiscussionForum", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("DiscussionForums")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Discussion_forum__30C33EC3");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.EmotionalFeedback", b =>
                {
                    b.HasOne("WebApplication6.Models.LearningActivity", "Activity")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__activ__6383C8BA");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__Learn__628FA481");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.EmotionalfeedbackReview", b =>
                {
                    b.HasOne("WebApplication6.Models.EmotionalFeedback", "Feedback")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Feedb__6E01572D");

                    b.HasOne("WebApplication6.Models.Instructor", "Instructor")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Instr__6EF57B66");

                    b.Navigation("Feedback");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("WebApplication6.Models.FilledSurvey", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSur__Learn__0D7A0286");

                    b.HasOne("WebApplication6.Models.SurveyQuestion", "SurveyQuestion")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("SurveyId", "Question")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSurvey__0C85DE4D");

                    b.Navigation("Learner");

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("WebApplication6.Models.HealthCondition", b =>
                {
                    b.HasOne("WebApplication6.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("HealthConditions")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HealthCondition__412EB0B6");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("WebApplication6.Models.InteractionLog", b =>
                {
                    b.HasOne("WebApplication6.Models.LearningActivity", "Activity")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__activ__5EBF139D");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__Learn__5FB337D6");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.Learner", b =>
                {
                    b.HasOne("WebApplication6.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication6.Models.LearnerDiscussion", b =>
                {
                    b.HasOne("WebApplication6.Models.DiscussionForum", "Forum")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Forum__339FAB6E");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Learn__3493CFA7");

                    b.Navigation("Forum");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.LearnerMastery", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("LearnerMasteries")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerMa__Learn__2DE6D218");

                    b.HasOne("WebApplication6.Models.SkillMastery", "Quest")
                        .WithMany("LearnerMasteries")
                        .HasForeignKey("QuestId")
                        .HasPrincipalKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerMa__Quest__2CF2ADDF");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebApplication6.Models.LearnersCollaboration", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Learn__29221CFB");

                    b.HasOne("WebApplication6.Models.Collaborative", "Quest")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Quest__2A164134");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebApplication6.Models.LearningActivity", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("LearningActivities")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_activit__5BE2A6F2");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.LearningPath", b =>
                {
                    b.HasOne("WebApplication6.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("LearningPaths")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_path__66603565");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("WebApplication6.Models.LearningPreference", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithOne("LearningPreference")
                        .HasForeignKey("WebApplication6.Models.LearningPreference", "LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__Learn__3B75D760");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.Module", b =>
                {
                    b.HasOne("WebApplication6.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Modules__CourseI__49C3F6B7");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebApplication6.Models.ModuleContent", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("ModuleContents")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ModuleContent__4F7CD00D");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.Pathreview", b =>
                {
                    b.HasOne("WebApplication6.Models.Instructor", "Instructor")
                        .WithMany("Pathreviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Pathrevie__Instr__6B24EA82");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("WebApplication6.Models.PersonalizationProfile", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("PersonalizationProfiles")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Personali__Learn__3E52440B");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.QuestReward", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("QuestRewards")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Learn__395884C4");

                    b.HasOne("WebApplication6.Models.Quest", "Quest")
                        .WithMany("QuestRewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Quest__3864608B");

                    b.HasOne("WebApplication6.Models.Reward", "Reward")
                        .WithMany("QuestRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Rewar__37703C52");

                    b.Navigation("Learner");

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("WebApplication6.Models.Ranking", b =>
                {
                    b.HasOne("WebApplication6.Models.Leaderboard", "Board")
                        .WithMany("Rankings")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__BoardID__7D439ABD");

                    b.HasOne("WebApplication6.Models.Course", "Course")
                        .WithMany("Rankings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__CourseI__7F2BE32F");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("Rankings")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__Learner__7E37BEF6");

                    b.Navigation("Board");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.Skill", b =>
                {
                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("Skills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skills__LearnerI__38996AB5");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.SkillMastery", b =>
                {
                    b.HasOne("WebApplication6.Models.Quest", "Quest")
                        .WithOne("SkillMastery")
                        .HasForeignKey("WebApplication6.Models.SkillMastery", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skill_Mas__Quest__236943A5");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebApplication6.Models.SkillProgression", b =>
                {
                    b.HasOne("WebApplication6.Models.Skill", "Skill")
                        .WithMany("SkillProgressions")
                        .HasForeignKey("LearnerId", "SkillName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SkillProgression__17F790F9");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebApplication6.Models.SurveyQuestion", b =>
                {
                    b.HasOne("WebApplication6.Models.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SurveyQue__Surve__09A971A2");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WebApplication6.Models.Takenassessment", b =>
                {
                    b.HasOne("WebApplication6.Models.Assessment", "Assessment")
                        .WithMany("Takenassessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenasse__Asses__59063A47");

                    b.HasOne("WebApplication6.Models.Learner", "Learner")
                        .WithMany("Takenassessments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenasse__Learn__5812160E");

                    b.Navigation("Assessment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("WebApplication6.Models.TargetTrait", b =>
                {
                    b.HasOne("WebApplication6.Models.Module", "Module")
                        .WithMany("TargetTraits")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Target_traits__4CA06362");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WebApplication6.Models.Assessment", b =>
                {
                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("WebApplication6.Models.Badge", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("WebApplication6.Models.Collaborative", b =>
                {
                    b.Navigation("LearnersCollaborations");
                });

            modelBuilder.Entity("WebApplication6.Models.Course", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Modules");

                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("WebApplication6.Models.DiscussionForum", b =>
                {
                    b.Navigation("LearnerDiscussions");
                });

            modelBuilder.Entity("WebApplication6.Models.EmotionalFeedback", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");
                });

            modelBuilder.Entity("WebApplication6.Models.Instructor", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");

                    b.Navigation("Pathreviews");
                });

            modelBuilder.Entity("WebApplication6.Models.Leaderboard", b =>
                {
                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("WebApplication6.Models.Learner", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("FilledSurveys");

                    b.Navigation("InteractionLogs");

                    b.Navigation("LearnerDiscussions");

                    b.Navigation("LearnerMasteries");

                    b.Navigation("LearnersCollaborations");

                    b.Navigation("LearningPreference");

                    b.Navigation("PersonalizationProfiles");

                    b.Navigation("QuestRewards");

                    b.Navigation("Rankings");

                    b.Navigation("Skills");

                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("WebApplication6.Models.LearningActivity", b =>
                {
                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("InteractionLogs");
                });

            modelBuilder.Entity("WebApplication6.Models.Module", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ContentLibraries");

                    b.Navigation("DiscussionForums");

                    b.Navigation("LearningActivities");

                    b.Navigation("ModuleContents");

                    b.Navigation("TargetTraits");
                });

            modelBuilder.Entity("WebApplication6.Models.PersonalizationProfile", b =>
                {
                    b.Navigation("HealthConditions");

                    b.Navigation("LearningPaths");
                });

            modelBuilder.Entity("WebApplication6.Models.Quest", b =>
                {
                    b.Navigation("Collaborative");

                    b.Navigation("QuestRewards");

                    b.Navigation("SkillMastery");
                });

            modelBuilder.Entity("WebApplication6.Models.Reward", b =>
                {
                    b.Navigation("QuestRewards");
                });

            modelBuilder.Entity("WebApplication6.Models.Skill", b =>
                {
                    b.Navigation("SkillProgressions");
                });

            modelBuilder.Entity("WebApplication6.Models.SkillMastery", b =>
                {
                    b.Navigation("LearnerMasteries");
                });

            modelBuilder.Entity("WebApplication6.Models.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("WebApplication6.Models.SurveyQuestion", b =>
                {
                    b.Navigation("FilledSurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
